keybord driver has been added

diff --git a/kernal/run b/kernal/run
--- a/kernal/run
+++ b/kernal/run
@@ -1,24 +1,30 @@
 #!/bin/bash
 
+DESABLED= false
+
 case $1 in
   -t)
-    echo "${BOLD}[+]${NC} cleaning files"
+    echo -e "${BOLD}[+]${NC} cleaning files"
     cargo clean
-    echo "${GREEN}[+]${NC} runnning tests"
-    cargo test --target x86_64-LunerOS.json || echo "${RED}[<!>]${NC} ${BOLD}an error happened${NC}"
+    echo -e "${GREEN}[+]${NC} runnning tests"
+    cargo test --target x86_64-LunerOS.json || echo -e -e "${RED}[<!>]${NC} ${BOLD}an error happened${NC}"
     exit
     ;;
   -b)
-    echo "${BOLD}[+]${NC} cleaning files"
+    echo -e "${BOLD}[+]${NC} cleaning files"
     cargo clean
-    echo "${BOLD}[+]${NC} building tree"
+    echo -e "${BOLD}[+]${NC} building tree"
     cargo build --target x86_64-LunerOS.json
     exit
     ;;
   -c)
-    echo "${BOLD}[+]${NC} cleaning files"
+    echo -e "${BOLD}[+]${NC} cleaning files"
     cargo clean
     exit
+    ;;
+  -e)
+    echo -e "${BOLD}[+]${NC} extras are desabled"
+    DESABLED= true
     ;;
   --tree)
     tree -L 3
@@ -26,7 +32,7 @@ case $1 in
     ;;
   --cat) 
     cat *
-    echo "\n"
+    echo -e "\n"
     exit
     ;;
 esac
@@ -35,55 +41,55 @@ START_TIME=$SECONDS
 
 clear
 
-echo -e "${GREEN}$(toilet -f mono12 runner)${NC}"
+echo "${GREEN}$(toilet -f mono12 runner)${NC}"
 echo "for LunerOS"
 
-echo "[+] initng"
+echo -e "${BOLD}[+]${NC} initng"
 GREEN='\033[1;32m'
 RED='\033[31m'
 BOLD='\033[1m'
 NC='\033[0m'
 
-echo "${BOLD}[+]${NC} cleaning files"
+echo -e "${BOLD}[+]${NC} cleaning files"
 cargo clean
 
-echo "${BOLD}[+]${NC} building tree"
+echo -e "${BOLD}[+]${NC} building tree"
 cargo build --target x86_64-LunerOS.json
 if ! cargo build --target x86_64-LunerOS.json; then
-    echo "${RED}[<!>]${NC} error: build failed"
+    echo -e "${RED}[<!>]${NC} error: build failed"
     fahh
     exit 1
 else
-    echo "${GREEN}[+]${NC} seccess"
-    exit
+    echo -e "${GREEN}[+]${NC} seccess"
 fi
-echo "[+] making bootimage"
+echo -e "${BOLD}[+]${NC} making bootimage"
 cargo bootimage
 
 DURATION=$(( SECONDS - START_TIME ))
-echo "[+] executed in $DURATION s"
+echo -e "${BOLD}[+]${NC} executed in $DURATION s"
 sleep 0.1
 
-echo '[+] running'
+echo -e '${BOLD}[+]${NC} running'
+cargo run
 
-qemu-system-x86_64 -drive format=raw,file=target/x86_64-LunerOS/debug/bootimage-LunerOS.bin -serial stdio
+if [[ $DESABLED ]]; then
+    echo -e "${BOLD}[+]${NC} do you want to run a debug? [y/n] or clean [c] or test [t]"
+    read debig
+    if [ $debig == "y" ]; then  
+        qemu-system-x86_64 -drive format=raw,file=target/x86_64-LunerOS/debug/bootimage-LunerOS.bin -d int,cpu_reset -no-reboot
+        exit
 
-echo "[+] do you want to run a debug? [y/n] or clean [c] or test [t]"
-read debig
-if [ $debig == "y" ]; then
-    qemu-system-x86_64 -drive format=raw,file=target/x86_64-LunerOS/debug/bootimage-LunerOS.bin -d int,cpu_reset -no-reboot
-    exit
+    elif [ $debig == "c" ]; then
+        cargo clean
+        clear
+        exit
 
-elif [ $debig == "c" ]; then
-    cargo clean
-    clear
-    exit
-
-elif [ $debig == "t" ]; then
-    cargo clear
-    cargo test
-    exit
-else
-    echo "[+] ok :D"
-    exit
+    elif [ $debig == "t" ]; then  
+        cargo clear
+        cargo test
+        exit
+    else  
+        echo -e "${BOLD}[+]${NC} ok :D"
+        exit
+    fi
 fi
